In [1]:
!python -m pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [2]:
import numpy as np

In [3]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12, 24).reshape(3,4)

print(a1, a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [4]:
a1 *2 

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [5]:
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [6]:
a1 > 5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [7]:
a1 == 34

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [8]:
# array function (math funtions)
a3 = np.random.random((3,3))

a3

array([[0.60388795, 0.0952808 , 0.01379857],
       [0.2383629 , 0.30373653, 0.46648174],
       [0.12762316, 0.79060691, 0.18045858]])

In [9]:
a3 = np.round(a1*100)
a3

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

In [10]:
np.max(a3)

1100

In [11]:
np.min(a3)

0

In [12]:
np.sum(a3)

6600

In [13]:
np.prod(a3)

0

In [14]:
np.min(a3, axis=1)

array([  0, 400, 800])

In [15]:
np.max(a3, axis=1)

array([ 300,  700, 1100])

In [16]:
np.max(a3, axis=0)

array([ 800,  900, 1000, 1100])

In [17]:
np.mean(a3)

550.0

In [18]:
np.mean(a3, axis=1)

array([150., 550., 950.])

In [19]:
np.median(a3)

550.0

In [20]:
np.median(a3, axis=0)

array([400., 500., 600., 700.])

In [21]:
np.std(a3)

345.2052529534663

In [22]:
np.var(a3)

119166.66666666667

In [23]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12, 24).reshape(4, 3)

print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [24]:
np.dot(a1, a2)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [25]:
np.exp(a1)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [26]:
np.round(np.random.random((2,3)) * 100)

array([[52., 13., 17.],
       [13., 14., 17.]])

In [27]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [28]:
a2[1, 2]

6

In [29]:
a3[1,0,1]

5

In [30]:
a3[0, 0, 0]

0

In [31]:
a3[1, 1, 0]

6

In [32]:
a1[2 : 5]

array([2, 3, 4])

In [33]:
a1[2: 5 : 2]

array([2, 4])

In [34]:
a2[0]

array([0, 1, 2, 3])

In [35]:
a2[:, 2]

array([ 2,  6, 10])

In [36]:
a2[1:, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [37]:
a2[::2, ::3 ]

array([[ 0,  3],
       [ 8, 11]])

In [38]:
a2[::2, 1::2]

array([[ 1,  3],
       [ 9, 11]])

In [39]:
a2[1, 0::3]

array([4, 7])

In [40]:
a2[0:2:, 1::]

array([[1, 2, 3],
       [5, 6, 7]])

In [41]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [42]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [43]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [44]:
a3[0, :]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [45]:
a3[1, :, 1]

array([10, 13, 16])

In [46]:
a3[2, 1:, 1:]

array([[22, 23],
       [25, 26]])

In [47]:
a3[::2, 0, ::2]

array([[ 0,  2],
       [18, 20]])

In [48]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [49]:
np.ravel(a3)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [50]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12, 24).reshape(3, 4)
print(a4)
print(a5)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [51]:
np.hstack((a4, a5, a4))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11]])

In [52]:
np.vstack((a4, a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [53]:
np.hsplit(a4, 2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [54]:
np.vsplit(a5, 3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]

In [59]:
a = np.arange(24).reshape(6, 4)

a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [63]:
a[[0, 2, 3, 5]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [65]:
a[:, [0, 2, 3]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

In [68]:
# Boolean indexing

a = np.random.randint(1, 100, 24).reshape(6, 4)

a

array([[ 9, 65, 88, 22],
       [67, 48, 68, 67],
       [77, 63, 19, 46],
       [ 7, 32, 62, 19],
       [19, 75, 23, 84],
       [13,  1, 21, 55]])

In [71]:
a[a > 50]

array([65, 88, 67, 68, 67, 77, 63, 62, 75, 84, 55])

In [72]:
# find even numbers
a[(a % 2) == 0]

array([88, 22, 48, 68, 46, 32, 62, 84])

In [76]:
# find even numbers greater than 50
a[(a > 50) & ((a % 2) == 0)]

array([88, 68, 62, 84])